import "./globals.css";
import 'shared-ui/node_modules/@material-tailwind/html/styles/material-tailwind.css';

import { Inter } from "next/font/google";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <script async src="https://unpkg.com/@material-tailwind/html@latest/scripts/ripple.js"></script>
      <body className={inter.className}>{children}
      </body>
    </html>
  );
}
