# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
name: End 2 End

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        # env:
        #   client-directory: ./Client
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js v12.19.0
              uses: actions/setup-node@v1
              with:
                  node-version: v12.19.0
            - run: |
                  npm ci
                  npm run build --if-present
                  npm start & npx wait-on http://localhost:3000
              # working-directory: ${{env.client-directory}}

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  browser: chrome
                  headless: true
                  env: host=http://localhost:3000
